---
title: "DTU_vulcano_ms"
author: "Gijsje"
date: "5/13/2021"
output: 
 rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r setup, include=FALSE}
library('variancePartition')
library('edgeR')
library(dplyr)
library(tidyr)
library(readxl)
library(edgeR)
library(limma)
library(DESeq2)
library(tidyverse)
library(data.table)
library(shiny)
library(pheatmap)
library(ggfortify)
library(ggplot2)
library(UpSetR)
library(VennDiagram)
library(knitr) 
library(tidyverse)
library(dplyr)
library(tidyr)
library(tibble)
library(purrr)
library(corrplot)
library(ggplot2)
library(ggpubr)
library(EnhancedVolcano)
library(readxl)
```

# Data load
# LPS

```{r Patir, echo = TRUE}
Patir <- read.csv("~/Documents/MiGASti/Databases/Patir.txt", sep="")
names(Patir)[1] <- "symbol"
```

# LPS

```{r vul_LPS, echo = TRUE}
load("~/Documents/MiGASti/Databases/splicing_dtu_stimulation_microglia.Rdata")
res <- all_res$LPS
res <- res[!duplicated(res$gene), ]
rownames(res) <- res$gene
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'pval')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'empirical_FDR',
    selectLab = c('CD44', 'TYROBP', 'GAS7', 'ITGB8', 'TMEM219', 'IFI30', 'DNAAF1'),
    xlab = bquote(~'estimates'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, empirical_FDR < 0.05)
sign_LF <- subset(sign, estimates > 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates > 1)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < -1)
length(sign_LF$gene)
```


# IFNy

```{r vul_IFNy, echo = TRUE}
res <- all_res$IFNy
res <- res[!duplicated(res$gene), ]
rownames(res) <- res$gene
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'pval')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'empirical_FDR',
    selectLab = c('WARS', 'IDO1', 'C2', 'CCRL2', 'CLU', 'CIITA'),
    xlab = bquote(~'estimates'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, empirical_FDR < 0.05)
sign_LF <- subset(sign, estimates > 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates > 1)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < -1)
length(sign_LF$gene)
```


# TNFa

```{r Vul_TNFa, echo = TRUE}
res <- all_res$TNFa
res <- res[!duplicated(res$gene), ]
rownames(res) <- res$gene
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'pval')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'empirical_FDR',
    selectLab = c('PSMB9', 'OSBPL8', 'TPM4', 'FKBP1A', 'B2M', 'KRAS'),
    xlab = bquote(~'estimates'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, empirical_FDR < 0.05)
sign_LF <- subset(sign, estimates > 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates > 1)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < -1)
length(sign_LF$gene)

```

# R848

```{r vul_R848, echo = TRUE}
res <- all_res$R848
res <- res[!duplicated(res$gene), ]
rownames(res) <- res$gene
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'pval')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'empirical_FDR',
    selectLab = c('SPPI', 'CXCL3', 'WDR74', 'GLS', 'ANXA2', 'TNFSR12A'),
    xlab = bquote(~'estimates'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, empirical_FDR < 0.05)
sign_LF <- subset(sign, estimates > 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates > 1)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < -1)
length(sign_LF$gene)
```


# DEX 

```{r vul_DEX, echo = TRUE}
res <- all_res$DEX
res <- res[!duplicated(res$gene), ]
rownames(res) <- res$gene
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'pval')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'empirical_FDR',
    selectLab = c('FKBP5'),
    xlab = bquote(~'estimates'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, empirical_FDR < 0.05)
sign_LF <- subset(sign, estimates > 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates > 1)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < -1)
length(sign_LF$gene)
```

# IL4 

```{r vul_IL4, echo = TRUE}
res <- all_res$IL4
res <- res[!duplicated(res$gene), ]
rownames(res) <- res$gene
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'pval')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'empirical_FDR',
    selectLab = c('NANS', 'ZEFF1', 'ARHGAP25', 'PSMB4', 'PSMB7', 'RBKS', 'HLA-DQA1', 'MARS'),
    xlab = bquote(~'estimates'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, empirical_FDR < 0.05)
sign_LF <- subset(sign, estimates > 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates > 1)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < -1)
length(sign_LF$gene)
```


# ATP

```{r vul_ATP, echo = TRUE}
res <- all_res$ATP
res <- res[!duplicated(res$gene), ]
rownames(res) <- res$gene
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'pval')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'estimates',
    y = 'empirical_FDR',
    selectLab = c('MTPAP', 'PSMB7', 'CSF3', 'TMEM183A', 'CCL3L1', 'CD44', 'IL1B', 'TSR1'),
    xlab = bquote(~'estimates'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, empirical_FDR < 0.05)
sign_LF <- subset(sign, estimates > 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < 0)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates > 1)
length(sign_LF$gene)

sign_LF <- subset(sign, estimates < -1)
length(sign_LF$gene)
```
