---
title: "DREAM_cultured_uncultured"
author: "Gijsje"
date: "5/13/2021"
output: 
 rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---


```{r setup, include = FALSE}
library('variancePartition')
library('edgeR')
library(dplyr)
library(tidyr)
library(rtracklayer)
library(ggplot2)
library(kableExtra)
library(data.table)
```

```{r Helper Functions, echo = FALSE}
createDT <- function(DF, caption="", scrollY=500){
data <- DT::datatable(DF, caption=caption,
extensions = 'Buttons',
options = list( dom = 'Bfrtip',
buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
scrollY = scrollY, scrollX=T, scrollCollapse = T, paging = F,
columnDefs = list(list(className = 'dt-center', targets = "_all"))
)
)
return(data)
}
```


# Load data 

```{r load, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
#load gene matrix
load("~/Documents/MiGASti/Databases/gene_matrix.RData")
#import dataset metadata
metadata <- read.table("~/Documents/MiGASti/Databases/metadata.txt", quote="\"", comment.char="")
gencode <- rtracklayer::import("gencode.v30.genes.gtf", format = "GTF")
#set rownames to Sample
row.names(metadata) <- metadata$Sample
#exclude samples that did not pass QC
exclude <- read.csv("~/Documents/MiGASti/Databases/samples2remove.txt", sep="")
exclude <- exclude$x
genes_counts_filt = genes_counts[, !colnames(genes_counts) %in% exclude]
#Excludes the samples from filters.
#dim(genes_counts_filt)
metadata_filt = metadata[ !(rownames(metadata) %in% exclude), ]
length(metadata_filt)
#remove low count genes
cpm <- cpm(genes_counts_filt)
# CPM >= 1 in at least 50% of the samples
keep.exp <- rowSums(cpm > 1) >= (0.5 * ncol(genes_counts_filt) )
genes_counts_filt1 <- genes_counts_filt[ keep.exp, ] #18997 genes
gene_id <- gencode$gene_id
#order metadata and genes counts
genes_counts_ordered <- genes_counts_filt1[,rownames(metadata_filt)]
#head(genes_counts_ordered)
all(rownames(metadata_filt) == colnames (genes_counts_ordered)) #TRUE
```


### Metadata 
#1.Donors
#2.Samples

```{r metadata, echo = TRUE}
samples_baseline = metadata_filt$Sample[metadata_filt$Stimulation %in% "ununstim"] # Includes same donor 
samples_condition = metadata_filt$Sample[metadata_filt$Stimulation %in% "unstim"] # Includes same donor  

metadata4deg = metadata_filt[rownames(metadata_filt) %in% c(samples_baseline,samples_condition) ,]

genes_baseline_condition = as.data.frame(genes_counts_ordered[, colnames(genes_counts_ordered) %in% c(samples_baseline, samples_condition)])
# dim(genes_voom_baseline_condition)
# dim(metadata4deg)

#remove samples in genes counts datafile
#genes_counts_cultured <- genes_counts_ordered2[,metadata_cultured$Sample]
experimentBycondition = unique(metadata4deg[,c("Donor_id", "Stimulation")])
#createDT(experimentBycondition)
as.data.frame(t(as.matrix(unclass(  table(experimentBycondition$Stimulation, useNA = "ifany"))))) %>%
kable(row.names = F) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

#genes_counts_cultured <- genes_counts_ordered2[,metadata_cultured$Sample]
experimentBycondition = unique(metadata4deg[,c("Sample", "Stimulation")])
#createDT(experimentBycondition)
as.data.frame(t(as.matrix(unclass(  table(experimentBycondition$Stimulation, useNA = "ifany"))))) %>%
kable(row.names = F) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### DREAM model 

```{r DREAM, echo = TRUE}
# The variable to be tested must be a fixed effect
names(metadata4deg) = tolower(names(metadata4deg))

#not corrected for region!

form <- ~ age + (1|donor_id) + stimulation + sex + picard_pct_ribosomal_bases + picard_pct_mrna_bases + picard_pct_percent_duplication + picard_pct_pf_reads_aligned 

# estimate weights using linear mixed model of dream
#vobjDream = voomWithDreamWeights( genes_baseline_condition, form, metadata4deg)

# Fit the dream model on each gene
#fit = (dream( vobjDream, form, metadata4deg ))

# Results generated
#res_cultured_uncultured <- data.frame(topTable(fit, coef='stimulationununstim', number=nrow(genes_counts_cultured), sort.by = "p"), check.names = F)
#save(res_uncultured_cultured, file ="res_uncultured_cultured.Rdata")
```


### DE genes 15% 

```{r DE_15, echo = TRUE}
load("~/Documents/MiGASti/Databases/res_uncultured_cultured.Rdata")
load("~/Downloads/genes_counts_cultured.Rdata")
res_cult <- res_uncultured_cultured
gencode_30 = read.table("~/Documents/MiGASti/Databases/ens.geneid.gencode.v30")
colnames(gencode_30) = c("ensembl","symbol")
res_cult <- tibble::rownames_to_column(res_cult, "ensembl")
res_name_cult <- merge(res_cult, gencode_30, by = "ensembl")
sign_cult <- subset(res_name_cult, adj.P.Val < 0.15)
length(rownames(sign_cult))
```


### DE genes 10%

```{r DE10 , echo = TRUE}
sign_cult <- subset(res_name_cult, adj.P.Val < 0.10)
sign_cult
length(rownames(sign_cult))
```


### DE genes 5%

```{r DE5, echo = TRUE}
sign_cult <- subset(res_name_cult, adj.P.Val < 0.05)
sign_cult
length(rownames(sign_cult))
```


### FDR distibution

```{r FDRdistribution, echo = TRUE}
res = res_name_cult
p = ggplot(res, aes(P.Value))
p + geom_density(color="darkblue", fill="lightblue") +
theme_classic() +
ggtitle("FDR Distribution")
```

### Fold change distribution

```{r foldchangedistribution, echo = TRUE}
p = ggplot(res, aes(logFC))
p + geom_density(color = "darkblue", fill = "lightblue") +
theme_classic() +
ggtitle("Fold Change Distribution")
```


### MA plot 

```{r MAplot, echo = TRUE}
plot.data = res
plot.data$id = rownames(plot.data)
data = data.frame(plot.data)
data$P.Value = -log10(data$P.Value)
data$fifteen = as.factor(abs(data$adj.P.Val < 0.05))
ma = ggplot(data, aes(AveExpr, logFC, color = fifteen))
ma + geom_point() +
scale_color_manual(values = c("black", "red"), labels = c ("> 0.05", "< 0.05")) +
labs(title = "MA plot", color = "labels") +
theme_classic()
#theme(plot.title = element_text(hjust = 0.5)) + ylim (-10,10) + xlim(-4,22)
```


### Volcano plot 

```{r Volcano, echo = TRUE}
vp = ggplot(data, aes(logFC, P.Value, color = fifteen))
vp + geom_point() +
scale_color_manual(values = c("black", "red"), labels = c("> 0.05", "< 0.05")) +
labs(title = "Gene Level Volcano Plot", color = "FDR") +
#theme(plot.title = element_text(hjust = 0.5)) +
theme_classic() +
xlim(-10,10) + ylim(0, 10) + ylab("-log10 pvalue")
load("~/Documents/MiGASti/docs/res_name_LPS2.Rdata")
```


### Boxplot top 6 genes 
#note. pvalues based on wilcox test of log2(tpm)+1 without additional correction(not based on pvalue DEGs with DREAM)

```{r boxplot_sex, echo = TRUE}
#set rownames to Sample
genes_tpm_filt = genes_tpm[, !colnames(genes_tpm) %in% exclude] 
#Excludes the samples from filters. 
#dim(genes_tpm_filt)
metadata_filt = metadata[ !(rownames(metadata) %in% exclude), ]
length(metadata_filt)
gencode_30 <- read.delim("~/Documents/MiGASti/Databases/ens.geneid.gencode.v30")
colnames(gencode_30) = c("ensembl","symbol")
genes_tpm_filt = log2((genes_tpm_filt) + 1)
genes_tpm_filt <- as.data.frame(genes_tpm_filt)
genes_tpm_ordered <- genes_tpm_filt[,rownames(metadata_filt)]
#head(genes_tpm_ordered)
all(rownames(metadata_filt) == colnames (genes_tpm_ordered)) #TRUE


samples_baseline = metadata_filt$Sample[metadata_filt$Stimulation %in% "ununstim"] # Includes same donor 
samples_condition = metadata_filt$Sample[metadata_filt$Stimulation %in% "unstim"] # Includes same donor  

metadata4deg = metadata_filt[rownames(metadata_filt) %in% c(samples_baseline,samples_condition) ,]

genes_baseline_condition = as.data.frame(genes_tpm_ordered[, colnames(genes_tpm_ordered) %in% c(samples_baseline, samples_condition)])
# dim(genes_voom_baseline_condition)
# dim(metadata4deg)

#create top 6 genes from DEG
deg_lists = res_name_cult[order(res_name_cult$adj.P.Val) ,]
top_6 = head(deg_lists)
data.table(top_6)

#create dataframe
gene2check = as.data.frame(genes_baseline_condition[top_6$ensembl, ])

#merge dataframe with symbol (gene_id)
gene2check$ensembl = rownames(gene2check)
top_6 <- merge(gencode_30, top_6, by = "ensembl")
gene2check = merge(gene2check, top_6[, c("symbol.y", "ensembl")], by = "ensembl")

names(metadata4deg) = tolower(names(metadata4deg))

#create dataframe for plots
gene2check_m = melt(gene2check, id.vars = c("ensembl", "symbol.y"))
gene2check_charac = merge(gene2check_m, metadata4deg, by.x = "variable", by.y = "sample")

# show direction of effect for male versus female
ggplot(gene2check_charac, aes(x = stimulation, y = value, fill = stimulation)) +
  geom_boxplot(notch = F, na.rm = T) +
  geom_jitter() +
  theme_bw() + facet_wrap(~symbol.y, scales = "free_y") +
  ggpubr::stat_compare_means(label = "p.format", label.x.npc = "centre", method = "wilcox.test")
```

### Data table for download 

```{r download, echo = TRUE}
res_cult_diff_top = res_name_cult[, c("ensembl", "symbol", "logFC", "AveExpr", "t", "P.Value", "adj.P.Val", "z.std")]
createDT(res_cult_diff_top)
```

