---
title: "Brain markers"
author: "Gijsje"
date: "2/16/2021"
output: 
 rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r load.packages, echo=FALSE, message=FALSE, results='hide'}
library(readxl)
library(edgeR)
library(limma)
library(DESeq2)
library(tidyverse)
library(data.table)
library(pheatmap)
library(readxl) 
library(ComplexHeatmap)
library(RColorBrewer)
library(dplyr)
library(tidyverse)
library(ggsci)
library(factoextra)
library(ggsci)
library(amap)
library(scales)
library(ggeasy)
library(ggtext)


knitr::opts_chunk$set( 
  warning=FALSE,
  message=FALSE,
  results = 'asis',
  error = FALSE,
  tidy = FALSE,
  fig.show = "hold")
```

# Brain markers in ex vivo vs in vitro (check also PDF for more detail about sample)

```{r data_load_markers, echo = TRUE, results = 'hide'}
load("~/Documents/MiGASti/Databases/gene_matrix.RData")
metadata <- read.table("~/Documents/MiGASti/Databases/metadata.txt")
#set rownames to Sample
row.names(metadata) <- metadata$Sample 
setwd("~/Documents/MiGASti/Databases")
exclude <- read.table("samples2remove.txt")
exclude <- exclude$x
genes_tpm_filt = genes_tpm[, !colnames(genes_tpm) %in% exclude] 
#Excludes the samples from filters. 
#dim(genes_tpm_filt)
metadata_filt = metadata[ !(rownames(metadata) %in% exclude), ]
length(metadata_filt)
#check for expression of markers in dataset
markers = "~/Documents/MiGASti/Databases/Markers.xlsx"
markers = read_excel(markers, col_names = TRUE) 
markers = as.data.frame(markers)
gencode_30 = read.table("~/Documents/MiGASti/Databases/ens.geneid.gencode.v30")
colnames(gencode_30) = c("ensembl","symbol")
genes_tpm_filt = log2((genes_tpm_filt) + 1)
genes_tpm_filt <- as.data.frame(genes_tpm_filt)

#select samples in dataset
metadata_cultured <- subset(metadata_filt, Stimulation == "unstim" | Stimulation == "ununstim")
#remove samples in genes counts datafile 
genes_tpm_cultured <- genes_tpm_filt[,metadata_cultured$Sample]

setDT(genes_tpm_cultured, keep.rownames = "ensembl")
res_name = merge(genes_tpm_cultured, gencode_30, by="ensembl")
rownames(res_name) = res_name$ensembl

marker_expression = merge(res_name, markers, by ="symbol")
rownames(marker_expression) = marker_expression$symbol
marker_expression$ensembl <- NULL
df_num = as.matrix(marker_expression[,2:178])
rownames(df_num) = marker_expression$symbol

#plot the genes based on samples 

metadata_cultured$Stimulation <- as.factor(metadata_cultured$Stimulation)
metadata_filt2 <- metadata_cultured[order(metadata_cultured$Stimulation, decreasing = T), ]
df <- t(df_num)
sorted <- df[rownames(metadata_filt2),]
sorted2 <- scale(sorted)
sorted2 <- t(sorted2)

ann <- data.frame(metadata_filt2$Stimulation)
colnames(ann) <- c('stimulation')
colours <- list('stimulation' = c('unstim' = 'royalblue',  'ununstim'  = 'navy'))
colAnn <- HeatmapAnnotation(df = ann,
  which = 'col',
  col = colours,
  annotation_width = unit(c(1, 4), 'cm'),
  gap = unit(1, 'mm'))

rownames(marker_expression) = marker_expression$symbol
cell_type = marker_expression$Cell_type  # keep in same gene order 
marker_expression$ensembl = NULL
df_num = as.matrix(marker_expression[,2:178])
rownames(df_num) = marker_expression$symbol

cell_type = as.factor(cell_type)
# cell_type_colors <- data.frame(cell_type = levels(cell_type), color = I(brewer.pal(nlevels(cell_type), name = 'Dark2')))
cell_type_colors <- data.frame(cell_type = levels(cell_type), color = pal_lancet('lanonc')(nlevels(cell_type)))
cell_type_df = left_join(data.frame(cell_type = cell_type), cell_type_colors, by="cell_type")
res <- unlist(lapply(split(cell_type_colors$color, cell_type_colors$cell_type), unlist))
row_ha = rowAnnotation(`Cell Type` = as.factor(cell_type_df$cell_type), col = list(`Cell Type` = res), show_annotation_name = F)


#pdf(file = "~/Documents/MiGASti/Databases/Brain_markers.pdf", width = 100,
#height = 6)
colPalette <- colorRampPalette(rev(brewer.pal(10, "RdYlBu")))(10)
Heatmap(sorted2,
        col = colPalette,
        name = "log2(TPM+1)", # Legend title
        cluster_rows = T,
        cluster_columns = T,
        # row_names_gp = gpar(fontsize = 4), # Text size for row names)
        show_column_dend = F, 
        show_column_names = F,
        show_row_names = T,
        column_split = rep(c(metadata_filt2$Stimulation)),
        top_annotation = colAnn,
        right_annotation = row_ha)
#dev.off()
```



