---
title: "Variance_partition"
author: "Gijsje"
date: "2/11/2021"
output:
  rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true 
---

```{r load.packages, echo=FALSE, message=FALSE, results='hide'}
library(variancePartition)
library(edgeR)

knitr::opts_chunk$set( 
  warning=FALSE,
  message=FALSE,
  results = 'asis',
  error = FALSE,
  tidy = FALSE,
  fig.show = "hold")
```

```{r load_data, echo=FALSE}
load("~/Documents/MiGASti/Databases/gene_matrix.RData")
metadata <- read.table("~/Documents/MiGASti/Databases/metadata.txt")
#set rownames to Sample
row.names(metadata) <- metadata$Sample
#exclude samples that did not pass QC
setwd("~/Documents/MiGASti/Databases")
exclude <- read.table("samples2remove.txt")
exclude <- exclude$x
genes_counts_filt = genes_counts[, !colnames(genes_counts) %in% exclude] 
dim(genes_counts_filt)
metadata_filt = metadata[ !(rownames(metadata) %in% exclude), ]
length(metadata_filt)
#remove low count genes
cpm <- cpm(genes_counts_filt) 
# CPM >= 1 in at least 50% of the samples
keep.exp <- rowSums(cpm > 1) >= (0.5 * ncol(genes_counts_filt) )
genes_counts5 <- genes_counts_filt[ keep.exp, ] #18997 genes 
#performing voom normalisation on data
counts_voom <- limma::voom(genes_counts5)
genes_counts_voom <- counts_voom$E
#order metadata and genes counts
rownames(metadata)
colnames(genes_counts_voom)
genes_counts_ordered <- genes_counts_voom[,rownames(metadata_filt)]
head(genes_counts_ordered)
all(rownames(metadata) == colnames (genes_counts_ordered)) #TRUE
```

```{r load.data, echo=FALSE}
setwd("~/Documents/MiGASti/Databases")
exclude <- read.table("samples2remove.txt")
exclude <- exclude$x
genes_counts_filt = genes_counts_ordered[, !colnames(genes_counts_ordered) %in% exclude] 
#Excludes the samples from filters. 
# dim(genes_counts_ordered)
metadata_filt = metadata[ !(rownames(metadata) %in% exclude), ]
length(metadata_filt)
```

```{r variance, echo = TRUE}
# For categorical covariates you need to include the number 1. Example: (1|Status) + (1|Plate)
#Based on Rsquared heatmap: highest correlation with PCs 

names(metadata_filt) = tolower(names(metadata_filt))

form <- ~ age + (1|donor_id) + picard_pct_ribosomal_bases + (1|region)  + picard_pct_mrna_bases + (1|sex)  + picard_pct_percent_duplication + picard_pct_pf_reads_aligned 

varPart_tx <- fitExtractVarPartModel(genes_counts_filt, form, metadata_filt)
```

```{r echo = FALSE}
vp <- sortCols( varPart_tx )
plotVarPart(vp)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
