
---
title: "20211503_DREAM_ununstim_unstim"
author: "Gijsje"
date: "3/15/2021"
output: 
rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r setup, include=FALSE}
library('variancePartition')
library('edgeR')
library('BiocParallel')
library(dplyr)
library(tidyr)
```

#DREAM ununstim vs unstim

```{r kable, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
#load gene matrix
load("~/MiGASti/gene_matrix.Rdata")
#import dataset metadata
metadata <- read.table("~/metadata2.txt", quote="\"", comment.char="")
#set rownames to Sample
row.names(metadata) <- metadata$Sample
#exclude samples that did not pass QC
exclude <- read.csv("~/samples2remove2.txt", sep="")
exclude <- exclude$x
genes_counts_filt = genes_counts[, !colnames(genes_counts) %in% exclude] 
#Excludes the samples from filters. 
#dim(genes_counts_filt)
metadata_filt = metadata[ !(rownames(metadata) %in% exclude), ]
length(metadata_filt)
#remove low count genes
cpm <- cpm(genes_counts_filt) 
# CPM >= 1 in at least 50% of the samples
keep.exp <- rowSums(cpm > 1) >= (0.5 * ncol(genes_counts_filt) )
genes_counts_filt1 <- genes_counts_filt[ keep.exp, ] #18997 genes 
#order metadata and genes counts
genes_counts_ordered <- genes_counts_filt1[,rownames(metadata_filt)]
#head(genes_counts_ordered)
all(rownames(metadata_filt) == colnames (genes_counts_ordered)) #TRUE
```

# Dream Analysis: uncultured vs cultured microglia samples

```{r dupCor, eval=TRUE}
metadata_cultured <- metadata_filt[metadata_filt$Stimulation !="ununstim",]
metadata_cultured_subset <- metadata_cultured[metadata_cultured$Stimulation != "TNFa",]
genes_counts_cultured <- genes_counts_ordered[,metadata_cultured_subset$Sample]
dim(metadata_cultured_subset)
table(metadata_filt$Stimulation)

# The variable to be tested must be a fixed effect
names(metadata_cultured_subset) = tolower(names(metadata_cultured_subset))

metadata_cultured_subset$region = as.factor(metadata_cultured_subset$region)

form <- ~ 0 + age + (1|donor_id) + stimulation + sex + picard_pct_ribosomal_bases + picard_pct_mrna_bases + picard_pct_percent_duplication + picard_pct_pf_reads_aligned + region 

# estimate weights using linear mixed model of dream
#vobjDream = voomWithDreamWeights( genes_counts_cultured, form, metadata_cultured_subset)

# Fit the dream model on each gene
#fit = (dream( vobjDream, form, metadata_cultured_subset ))
```


```{r results_age, eval=TRUE}
#L1 = getContrast (vobjDream, form, metadata_cultured_subset, c("stimulationLPS", "stimulationunstim"))
#L2 = getContrast (vobjDream, form, metadata_cultured_subset, c("stimulationIFNy", "stimulationunstim"))
#L3 = getContrast (vobjDream, form, metadata_cultured_subset, c("stimulationIL4", "stimulationunstim"))
#L4 = getContrast (vobjDream, form, metadata_cultured_subset, c("stimulationDEX", "stimulationunstim"))
#L5 = getContrast (vobjDream, form, metadata_cultured_subset, c("stimulationR848", "stimulationunstim"))
#L6 = getContrast (vobjDream, form, metadata_cultured_subset, c("stimulationATP", "stimulationunstim"))
#L= cbind(L1, L2, L3, L4, L5, L6)
#plotContrasts(L)

#fit = dream(vobjDream, form, metadata_cultured_subset, L)

#res_LPS <- data.frame(topTable(fit, coef='L1', number=nrow(genes_counts_cultured), sort.by = "p"), check.names = F)
#res_IFNy <- data.frame(topTable(fit, coef='L2', number=nrow(genes_counts_cultured), sort.by = "p"), check.names = F)
#res_IL4 <- data.frame(topTable(fit, coef='L3', number=nrow(genes_counts_cultured), sort.by = "p"), check.names = F)
#res_DEX <- data.frame(topTable(fit, coef='L4', number=nrow(genes_counts_cultured), sort.by = "p"), check.names = F)
#res_R848 <- data.frame(topTable(fit, coef='L5', number=nrow(genes_counts_cultured), sort.by = "p"), check.names = F)
#res_ATP <- data.frame(topTable(fit, coef='L6', number=nrow(genes_counts_cultured), sort.by = "p"), check.names = F)

gencode_30 = read.table("~/Documents/MiGASti/Databases/ens.geneid.gencode.v30")
colnames(gencode_30) = c("ensembl","symbol")

#res_LPS <- tibble::rownames_to_column(res_LPS, "ensembl")
#res_LPS_name <- merge(res_LPS, gencode_30, by = "ensembl")
#res_IFNy <- tibble::rownames_to_column(res_IFNy_mono, "ensembl")
#res_IFNy_name <- merge(res_IFNy, gencode_30, by = "ensembl")

#save(res_LPS_name, file = "res_LPS_name.Rdata")
#save(res_IFNy_name, file = "res_IFNy_name.Rdata")

#res_IL4 <- tibble::rownames_to_column(res_IL4, "ensembl")
#res_IL4_name <- merge(res_IL4, gencode_30, by = "ensembl")
#res_DEX <- tibble::rownames_to_column(res_DEX, "ensembl")
#res_DEX_name <- merge(res_DEX, gencode_30, by = "ensembl")

#save(res_IL4_name, file = "res_IL4_name.Rdata")
#save(res_DEX_name, file = "res_DEX_name.Rdata")

#res_R848 <- tibble::rownames_to_column(res_R848, "ensembl")
#res_R848_name <- merge(res_848, gencode_30, by = "ensembl")
#res_ATP <- tibble::rownames_to_column(res_ATP, "ensembl")
#res_ATP_name <- merge(res_ATP, gencode_30, by = "ensembl")

#save(res_R848_name, file = "res_R848_name.Rdata")
#save(res_ATP_name, file = "res_ATP_name.Rdata")
```


```{r data_prep, eval=TRUE}
load("~/Documents/MiGASti/docs/2nd_pass/res_LPS_name.Rdata")
load("~/Documents/MiGASti/docs/2nd_pass/res_R848_name.Rdata")
load("~/Documents/MiGASti/docs/2nd_pass/res_IFNy_name.Rdata")
load("~/Documents/MiGASti/docs/2nd_pass/res_ATP_name.Rdata")
load("~/Documents/MiGASti/docs/2nd_pass/res_IL4_name.Rdata")
load("~/Documents/MiGASti/docs/2nd_pass/res_DEX_name.Rdata")

sign_LPS <- subset(res_LPS_name, adj.P.Val < 0.05)
LPS_up <- subset(sign_LPS, logFC > 1)
LPS_down <- subset(sign_LPS, logFC < -1)
library("writexl")
write_xlsx(LPS_up, "~/Documents/MiGASti/docs/2nd_pass/LPS_up.xlsx")
write_xlsx(LPS_down, "~/Documents/MiGASti/docs/2nd_pass/LPS_down.xlsx")

sign_IFNy <- subset(res_IFNy_name, adj.P.Val < 0.05)
IFNy_up <- subset(sign_IFNy, logFC > 1)
library("writexl")
write_xlsx(IFNy_up, "~/Documents/MiGASti/docs/2nd_pass/IFNy_up.xlsx")

sign_R848 <- subset(res_R848_name, adj.P.Val < 0.05)
R848_up <- subset(sign_R848, logFC > 1)
R848_down <- subset(sign_R848, logFC < -1)
library("writexl")
write_xlsx(R848_up, "~/Documents/MiGASti/docs/2nd_pass/R848_up.xlsx")
write_xlsx(R848_down, "~/Documents/MiGASti/docs/2nd_pass/R848_down.xlsx")

sign_DEX <- subset(res_DEX_name, adj.P.Val < 0.05)
DEX_up <- subset(sign_DEX, logFC > 1)
DEX_down <- subset(sign_DEX, logFC < -1)
library("writexl")
write_xlsx(DEX_up, "~/Documents/MiGASti/docs/2nd_pass/DEX_up.xlsx")
write_xlsx(DEX_down, "~/Documents/MiGASti/docs/2nd_pass/DEX_down.xlsx")

sign_ATP <- subset(res_ATP_name, adj.P.Val < 0.05)
ATP_up <- subset(sign_ATP, logFC > 1)
ATP_down <- subset(sign_ATP, logFC < -1)
library("writexl")
write_xlsx(ATP_up, "~/Documents/MiGASti/docs/2nd_pass/ATP_up.xlsx")
write_xlsx(ATP_down, "~/Documents/MiGASti/docs/2nd_pass/ATP_down.xlsx")

sign_IL4 <- subset(res_IL4_name, adj.P.Val < 0.05)
IL4_up <- subset(sign_IL4, logFC > 1)
library("writexl")
write_xlsx(IL4_up, "~/Documents/MiGASti/docs/2nd_pass/IL4_up.xlsx")
```
