
---
title: "20211503_DREAM_ununstim_unstim"
author: "Gijsje"
date: "3/15/2021"
output: 
rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r setup, include=FALSE}
library('variancePartition')
library('edgeR')
library('BiocParallel')
library(dplyr)
library(tidyr)
```

#DREAM ununstim vs unstim

```{r kable, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
#load gene matrix
load("~/MiGASti/gene_matrix.Rdata")
#import dataset metadata
metadata <- read.table("~/MiGASti/metadata2.txt", quote="\"", comment.char="")
#set rownames to Sample
row.names(metadata) <- metadata$Sample
#exclude samples that did not pass QC
exclude <- read.csv("~/MiGASti/samples2remove2.txt", sep="")
exclude <- exclude$x
genes_counts_filt = genes_counts[, !colnames(genes_counts) %in% exclude] 
#Excludes the samples from filters. 
#dim(genes_counts_filt)
metadata_filt = metadata[ !(rownames(metadata) %in% exclude), ]
length(metadata_filt)
#remove low count genes
cpm <- cpm(genes_counts_filt) 
# CPM >= 1 in at least 50% of the samples
keep.exp <- rowSums(cpm > 1) >= (0.5 * ncol(genes_counts_filt) )
genes_counts_filt1 <- genes_counts_filt[ keep.exp, ] #18997 genes 
#order metadata and genes counts
genes_counts_ordered <- genes_counts_filt1[,rownames(metadata_filt)]
#head(genes_counts_ordered)
all(rownames(metadata_filt) == colnames (genes_counts_ordered)) #TRUE
```

# Dream Analysis: uncultured vs cultured microglia samples

```{r dupCor, eval=TRUE}
samples_baseline = metadata_filt$Sample[metadata_filt$Stimulation %in% "ununstim"] # Includes same donor 
samples_condition = metadata_filt$Sample[metadata_filt$Stimulation %in% "unstim"] # Includes same donor  

metadata4deg = metadata_filt[rownames(metadata_filt) %in% c(samples_baseline,samples_condition) ,]

genes_baseline_condition = as.data.frame(genes_counts_ordered[, colnames(genes_counts_ordered) %in% c(samples_baseline, samples_condition)])
# dim(genes_voom_baseline_condition)
# dim(metadata4deg)

# The variable to be tested must be a fixed effect
names(metadata4deg) = tolower(names(metadata4deg))

metadata4deg$region = as.factor(metadata4deg$region)

form <- ~ age + (1|donor_id) + stimulation + sex + picard_pct_ribosomal_bases + picard_pct_mrna_bases + picard_pct_percent_duplication + picard_pct_pf_reads_aligned + region 

# estimate weights using linear mixed model of dream
vobjDream = voomWithDreamWeights( genes_baseline_condition, form, metadata4deg)

# Fit the dream model on each gene
fit = (dream( vobjDream, form, metadata4deg ))
```


```{r results_age, eval=TRUE}
res_uncultured_cultured <- data.frame(topTable(fit, coef='stimulationununstim', number=nrow(genes_baseline_condition), sort.by = "p"), check.names = F)
length(which(res_uncultured_cultured$adj.P.Val<0.05))
save(res_uncultured_cultured, file ="res_uncultured_cultured.Rdata")
```
