---
title: "Genelists_overlap"
author: "Gijsje"
date: "5/13/2021"
output: 
 rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r setup, include=FALSE}
library('variancePartition')
library('edgeR')
library(dplyr)
library(tidyr)
library(readxl)
library(edgeR)
library(limma)
library(DESeq2)
library(tidyverse)
library(data.table)
library(shiny)
library(pheatmap)
library(ggfortify)
library(ggplot2)
library(UpSetR)
library(VennDiagram)
library(knitr) 
library(tidyverse)
library(dplyr)
library(tidyr)
library(tibble)
library(purrr)
library(corrplot)
library(ggplot2)
library(ggpubr)
library(EnhancedVolcano)
library(raster)
library(dplyr)
library(ggrastr)
```

# All samples

```{r function_setenrichment, echo = TRUE}
# Function set enrichment
setEnrichment <- function(set1, set2, universe = 20000){

  a = sum(set1 %in% set2)

  c = length(set1) - a

  b = length(set2) - a

  d = universe - length(set2) - c

  contingency_table = matrix(c(a, c, b, d), nrow = 2)

  # one-tailed test for enrichment only

  fisher_results = fisher.test(contingency_table, alternative = "greater")

  # returns data.frame containing the lengths of the two sets, the overlap, the enrichment ratio (odds ratio) and P value

  df <- tibble::tibble( set1_length = length(set1), set2_length = length(set2), overlap = a, ratio = fisher_results$estimate, p.value = fisher_results$p.value)

  return(df)
}
```

# Data load

```{r Patir, echo = TRUE}
Patir <- read.csv("~/Documents/MiGASti/Databases/Patir.txt", sep="")
names(Patir)[1] <- "symbol"

ARM = "~/Documents/MiGASti/Databases/Activation_response_microglia.xlsx"
ARM = read_excel(ARM, col_names = TRUE) 
ARM = as.data.frame(ARM)

IRM = "~/Documents/MiGASti/Databases/Immediate_response_microglia.xlsx"
IRM = read_excel(IRM, col_names = TRUE) 
IRM = as.data.frame(IRM)

NFkB = "~/Documents/MiGASti/Databases/NfkB_activation.xlsx"
NFkB = read_excel(NFkB, col_names = TRUE) 
NFkB = as.data.frame(NFkB)

Cold = "~/Documents/MiGASti/Databases/Cold.xlsx"
Cold = read_excel(Cold, col_names = TRUE) 
Cold = as.data.frame(Cold)

SA_LPS = "~/Documents/MiGASti/Databases/subacute_microglia.xlsx"
SA_LPS = read_excel(SA_LPS, col_names = TRUE) 
SA_LPS = as.data.frame(SA_LPS)

A_LPS = "~/Documents/MiGASti/Databases/acute_LPS.xlsx"
A_LPS = read_excel(A_LPS, col_names = TRUE) 
A_LPS = as.data.frame(A_LPS)

InjRM = "~/Documents/MiGASti/Databases/Injury_responsive.xlsx"
InjRM = read_excel(InjRM, col_names = TRUE) 
InjRM = as.data.frame(InjRM)

AD = "~/Documents/MiGASti/Databases/Alzheimers_disease.xlsx"
AD = read_excel(AD, col_names = TRUE) 
AD = as.data.frame(AD)

MS = "~/Documents/MiGASti/Databases/Multiple_sclerosis.xlsx"
MS = read_excel(MS, col_names = TRUE) 
MS = as.data.frame(MS)

INV_down = "~/Documents/MiGASti/Databases/INVITRO_DOWN.xlsx"
INV_down = read_excel(INV_down, col_names = TRUE) 
INV_down = as.data.frame(INV_down)

DAM_down = "~/Documents/MiGASti/Databases/DAM_DOWN.xlsx"
DAM_down = read_excel(DAM_down, col_names = TRUE) 
DAM_down = as.data.frame(DAM_down)

DAM_up = "~/Documents/MiGASti/Databases/DAM_up.xlsx"
DAM_up = read_excel(DAM_up, col_names = TRUE) 
DAM_up = as.data.frame(DAM_up)

HAM_up = "~/Documents/MiGASti/Databases/HAM_up.xlsx"
HAM_up = read_excel(HAM_up, col_names = TRUE) 
HAM_up = as.data.frame(HAM_up)

HAM_down = "~/Documents/MiGASti/Databases/HAM_DOWN.xlsx"
HAM_down = read_excel(HAM_down, col_names = TRUE) 
HAM_down = as.data.frame(HAM_down)

INV_up = "~/Documents/MiGASti/Databases/INVITRO_UP.xlsx"
INV_up = read_excel(INV_up, col_names = TRUE) 
INV_up = as.data.frame(INV_up)

TWAS_PD = "~/Documents/MiGASti/Databases/TWAS_PD.xlsx"
TWAS_PD = read_excel(TWAS_PD, col_names = TRUE) 
TWAS_PD = as.data.frame(TWAS_PD)

TWAS_AD = "~/Documents/MiGASti/Databases/TWAS_PD.xlsx"
TWAS_AD = read_excel(TWAS_AD, col_names = TRUE) 
TWAS_AD = as.data.frame(TWAS_AD)

INFy_GO = "~/Documents/MiGASti/Databases/IFNy_GO.xlsx"
INFy_GO = read_excel(INFy_GO, col_names = TRUE) 
INFy_GO = as.data.frame(INFy_GO)

PIG = "~/Documents/MiGASti/Databases/PIG.xlsx"
PIG = read_excel(PIG, col_names = TRUE) 
PIG = as.data.frame(PIG)

Sensome = "~/Documents/MiGASti/Databases/Sensome_human.xlsx"
Sensome = read_excel(Sensome, col_names = TRUE) 
Sensome = as.data.frame(Sensome)

aging_down = "~/Documents/MiGASti/Databases/aging_down_MIGA.xlsx"
aging_down = read_excel(aging_down, col_names = TRUE) 
aging_down = as.data.frame(aging_down)

aging_up = "~/Documents/MiGASti/Databases/aging_up_MIGA.xlsx"
aging_up = read_excel(aging_up, col_names = TRUE) 
aging_up = as.data.frame(aging_up)
```

# LPS UP

```{r vul_LPS, echo = TRUE}
load("~/Documents/MiGASti/res_name_LPS2.Rdata")
res_LPS <- res_name_LPS2

sign <- subset(res_LPS, adj.P.Val < 0.05)
LPS_UP <- subset(sign, logFC > 1)

set1 <- LPS_UP
set1_v <- set1$symbol
set2_v <- set2$symbol

setEnrichment( set1 = set1_v, set2 = set2_v)
```
### + acute responsive microglia 

```{r LPS_ARM, echo = TRUE}
set2 <- ARM
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + immediate responsive microglia 

```{r LPS_IRM, echo = TRUE}
set2 <- IRM
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + NFkB GO 

```{r LPS_NFkB, echo = TRUE}
set2 <- NFkB
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + INFy GO

```{r LPS_NFkB, echo = TRUE}
set2 <- INFy_GO
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + Cold 

```{r LPS_COLD, echo = TRUE}
set2 <- Cold
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + acute_LPS 

```{r LPS_acute, echo = TRUE}
set2 <- A_LPS
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + subacute_LPS 

```{r LPS_subacute, echo = TRUE}
set2 <- SA_LPS
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + Injury responsive microglia 

```{r LPS_InjRM, echo = TRUE}
set2 <- InjRM
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + Plaque induced genes 

```{r LPS_PIG, echo = TRUE}
set2 <- PIG
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + Sensome genes 

```{r LPS_Sensome, echo = TRUE}
set2 <- Sensome
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + AD genes

```{r LPS_AD, echo = TRUE}
set2 <- AD
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + TWAS AD genes

```{r LPS_AD_TWAS, echo = TRUE}
set2 <- TWAS_AD
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + MS

```{r LPS_MS, echo = TRUE}
set2 <- MS
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + TWAS PD

```{r LPS_TWAS_PD, echo = TRUE}
set2 <- TWAS_PD
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + HAM_up

```{r LPS_HAM_up, echo = TRUE}
set2 <- HAM_UP
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + HAM_down

```{r LPS_HAM_down, echo = TRUE}
set2 <- HAM_DOWN
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + DAM_up

```{r LPS_DAM_up, echo = TRUE}
set2 <- DAM_UP
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + DAM_down

```{r LPS_DAM_down, echo = TRUE}
set2 <- DAM_DOWN
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + INV_up

```{r LPS_INV_up, echo = TRUE}
set2 <- INV_up
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + INV_down

```{r LPS_INV_down, echo = TRUE}
set2 <- INV_down
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + aging_up

```{r LPS_aging_up, echo = TRUE}
set2 <- aging_up
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```

### + aging_down

```{r LPS_aging_down, echo = TRUE}
set2 <- aging_down
set2_v <- set2$symbol
setEnrichment( set1 = set1_v, set2 = set2_v)
```



# IFNy

```{r vul_IFNy, echo = TRUE}
load("~/Documents/MiGASti/docs/res_name_IFNy2.Rdata")
res_IFNy <- res_name_IFNy2
res <- res_name_IFNy2[!duplicated(res_name_IFNy2$symbol), ]
rownames(res) <- res$symbol
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val')



sign <- subset(res, adj.P.Val < 0.05)
sign_LF <- subset(sign, logFC > 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC > 1)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < -1)
length(sign_LF$symbol)

```


# TNFa

```{r Vul_TNFa, echo = TRUE}
load("~/Documents/MiGASti/Databases/res_name_TNFa2.Rdata")
res <- res_name_TNFa2[!duplicated(res_name_TNFa2$symbol), ]
rownames(res) <- res$symbol
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val',
    selectLab = c('GGA2', 'IRF8', 'TNFRSF1B', 'LPAR5'),
    xlab = bquote(~Log[2]~ 'fold change'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, adj.P.Val < 0.05)
sign_LF <- subset(sign, logFC > 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < 0)
length(sign_LF$symbol)

overlap <- merge(sign_LF, Patir, by = "symbol")
list(overlap$symbol)

sign_LF <- subset(sign, logFC > 1)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < -1)
length(sign_LF$symbol)

```

# R848

```{r vul_R848, echo = TRUE}
load("~/Documents/MiGASti/Databases/res_name_R8482.Rdata")
res <- res_name_R8482[!duplicated(res_name_R8482$symbol), ]
rownames(res) <- res$symbol
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val',
    selectLab = c('TNF', 'IL6', 'IL12B', 'CSF3', 'GPAT3', 'RAB7B'),
    xlab = bquote(~Log[2]~ 'fold change'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, adj.P.Val < 0.05)
sign_LF <- subset(sign, logFC > 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC > 1)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < -1)
length(sign_LF$symbol)
```


# DEX 

```{r vul_DEX, echo = TRUE}
load("~/Documents/MiGASti/Databases/res_name_DEX2.Rdata")
res <- res_name_DEX2[!duplicated(res_name_DEX2$symbol), ]
rownames(res) <- res$symbol
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val',
    selectLab = c('FKBP5', 'ZBTB16', 'ALOX15B', 'PIK3IP1', 'CA12', 'TNFSF8'),
    xlab = bquote(~Log[2]~ 'fold change'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, adj.P.Val < 0.05)
sign_LF <- subset(sign, logFC > 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC > 1)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < -1)
length(sign_LF$symbol)
```

# IL4 

```{r vul_IL4, echo = TRUE}
load("~/Documents/MiGASti/Databases/res_name_IL42.Rdata")
res <- res_name_IL42[!duplicated(res_name_IL42$symbol), ]
rownames(res) <- res$symbol
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val',
    selectLab = c('SPINT2', 'CISH', 'CTSC', 'TGM2', 'MS4A4A', 'P2RY12', 'CLEC5A', 'ST3GAL1'),
    xlab = bquote(~Log[2]~ 'fold change'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, adj.P.Val < 0.05)
sign_LF <- subset(sign, logFC > 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC > 1)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < -1)
length(sign_LF$symbol)

overlap <- merge(sign_LF, Patir, by = "symbol")
list(overlap$symbol)
```


# ATP

```{r vul_ATP, echo = TRUE}
load("~/Documents/MiGASti/Databases/res_name_ATP2.Rdata")
res <- res_name_ATP2[!duplicated(res_name_ATP2$symbol), ]
rownames(res) <- res$symbol
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val')


EnhancedVolcano(res,
    lab = rownames(res),
    x = 'logFC',
    y = 'adj.P.Val',
    selectLab = c('NR4A3', 'OVOL1', 'PALM2', 'MICA'),
    xlab = bquote(~Log[2]~ 'fold change'),
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 2.0,
    labSize = 3.0,
    legendPosition = 'right',
    legendLabSize = 6,
    legendIconSize = 2.0)

sign <- subset(res, adj.P.Val < 0.05)
sign_LF <- subset(sign, logFC > 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < 0)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC > 1)
length(sign_LF$symbol)

sign_LF <- subset(sign, logFC < -1)
length(sign_LF$symbol)
```
