---
title: "Stimulations"
author: "Gijsje"
date: "2/16/2021"
output: 
 rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r load.packages, echo=FALSE, message=FALSE, results='hide'}
library(readxl)
library(edgeR)
library(limma)
library(DESeq2)
library(tidyverse)
library(data.table)
library(pheatmap)
library(readxl) 
library(ComplexHeatmap)
library(RColorBrewer)
library(dplyr)
library(tidyverse)
library(ggsci)
library(factoextra)
library(ggsci)
library(amap)
library(scales)
library(ggeasy)
library(ggtext)


knitr::opts_chunk$set( 
  warning=FALSE,
  message=FALSE,
  results = 'asis',
  error = FALSE,
  tidy = FALSE,
  fig.show = "hold")
```


```{r check, echo = TRUE, results = 'hide'}
load("~/Documents/MiGASti/Databases/gene_matrix.RData")
metadata <- read.table("~/Documents/MiGASti/Databases/metadata.txt")
#set rownames to Sample
row.names(metadata) <- metadata$Sample 
setwd("~/Documents/MiGASti/Databases")
exclude <- read.table("samples2remove.txt")
exclude <- exclude$x
genes_tpm_filt = genes_tpm[, !colnames(genes_tpm) %in% exclude] 
#Excludes the samples from filters. 
#dim(genes_tpm_filt)
metadata_filt = metadata[ !(rownames(metadata) %in% exclude), ]
length(metadata_filt)
#check for expression of markers in dataset
markers = "~/Documents/MiGASti/Databases/Lot_genes.xlsx"
markers = read_excel(markers, col_names = TRUE) 
markers = as.data.frame(markers)
gencode_30 = read.table("~/Documents/MiGASti/Databases/ens.geneid.gencode.v30")
colnames(gencode_30) = c("ensembl","symbol")
genes_tpm_filt = log2((genes_tpm_filt) + 1)
genes_tpm_filt <- as.data.frame(genes_tpm_filt)
setDT(genes_tpm_filt, keep.rownames = "ensembl")
genes_tpm_filt$ensembl
res_name = merge(genes_tpm_filt, gencode_30, by="ensembl")
rownames(res_name) = res_name$ensembl
```


```{r data_load_markers, echo = TRUE, results = 'hide'}
marker_expression = merge(res_name, markers, by ="symbol")
dim (marker_expression)
head (marker_expression)
metadata_filt_ordered <- metadata_filt[colnames(genes_tpm_filt),]
metadata_filt_ordered = metadata_filt_ordered[-1,]
all(rownames(metadata_filt_ordered) == colnames (genes_tpm_filt)) #TRUEgit 
Stimulation <- metadata_filt_ordered$Stimulation
```
### Boxplot  MECP2

```{r MECP2, echo = TRUE}
MECP2 <- marker_expression[5, ] 
MECP2$ensembl = NULL
MECP2$symbol = NULL
MECP2_new<-as.data.frame(t(MECP2))
df = data.frame(Stimulation, MECP2_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("MECP2") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```

### Boxplot  KDM6B

```{r KDM6B, echo = TRUE}
KDM6B <- marker_expression[3, ] 
KDM6B$ensembl = NULL
KDM6B$symbol = NULL
KDM6B_new<-as.data.frame(t(KDM6B))
df = data.frame(Stimulation, KDM6B_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("KDM6B") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```


### Boxplot  EHMT1

```{r EHMT1, echo = TRUE}
EHMT1 <- marker_expression[2, ] 
EHMT1$ensembl = NULL
EHMT1$symbol = NULL
EHMT1_new<-as.data.frame(t(EHMT1))
df = data.frame(Stimulation, EHMT1_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("EHMT1") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```



### Boxplot  MAOA

```{r MAOA1, echo = TRUE}
MAOA <- marker_expression[4, ] 
MAOA$ensembl = NULL
MAOA$symbol = NULL
MAOA_new<-as.data.frame(t(MAOA))
df = data.frame(Stimulation, MAOA_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("MAOA") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```


### Boxplot  DDX3X

```{r DDX3X, echo = TRUE}
DDX3X <- marker_expression[1, ] 
DDX3X$ensembl = NULL
DDX3X$symbol = NULL
DDX3X_new<-as.data.frame(t(DDX3X))
df = data.frame(Stimulation, DDX3X_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("DDX3X") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```

# Expression of neurodevelopmental markers

```{r data_load_heatmap, echo = TRUE, results='hide'}
rownames(marker_expression) = marker_expression$symbol
marker_expression$ensembl <- NULL
df_num = as.matrix(marker_expression[,2:497])
rownames(df_num) = marker_expression$symbol

#plot the genes based on samples 

metadata_filt$Stimulation <- as.factor(metadata_filt$Stimulation)
metadata_filt2 <- metadata_filt[order(metadata_filt$Stimulation, decreasing = T), ]
df <- t(df_num)
sorted <- df[rownames(metadata_filt2),]
sorted2 <- t(sorted)
sorted2 <- scale(sorted2)

ann <- data.frame(metadata_filt2$Stimulation)
colnames(ann) <- c('stimulation')
colours <- list('stimulation' = c('ununstim' = 'red2', 'unstim' = 'royalblue',  'TNFa'  = 'navy', 'R848'='green', 'LPS'='pink', 'IL4'='yellow', 'DEX'='orange', 'ATP'='brown', 'IFNy'='purple'))
colAnn <- HeatmapAnnotation(df = ann,
  which = 'col',
  col = colours,
  annotation_width = unit(c(1, 4), 'cm'),
  gap = unit(1, 'mm'))

```

```{r _heatmap, echo = TRUE, fig.width=10, fig.height=6, dpi=300}
#pdf(file = "~/Documents/MiGASti/Databases/Stim_markers.pdf", width = 100,
#height = 6)
colPalette <- colorRampPalette(rev(brewer.pal(11, "RdYlBu")))(496)
Heatmap(sorted2,
        col = colPalette,
        name = "log2(TPM+1)", # Legend title
        cluster_rows = T,
        cluster_columns = F,
        #  row_names_gp = gpar(fontsize = 6), # Text size for row names)
        show_column_dend = F, 
        show_column_names = F,
        show_row_names = T,
        column_split = rep(c(metadata_filt2$Stimulation)),
        top_annotation = colAnn)
#dev.off()
```


```{r data_load_heatmap_means, echo = TRUE, results='hide'}
rownames(marker_expression) = marker_expression$symbol
marker_expression$ensembl <- NULL
df_num = as.matrix(marker_expression[,2:497])
rownames(df_num) = marker_expression$symbol

#plot the genes based on samples 

metadata_filt$Stimulation <- as.factor(metadata_filt$Stimulation)
metadata_filt2 <- metadata_filt[order(metadata_filt$Stimulation, decreasing = T), ]
df <- t(df_num)
sorted <- df[rownames(metadata_filt2),]
sorted <- scale(sorted)
sorted2 <- t(sorted)

Stimulation <- metadata_filt2$Stimulation

df <- rbind(sorted2, Stimulation)
library(dplyr)
df2 <- t(df)
df3 <- as.data.frame(df2)
setDT(df3)
df4 <- df3 %>% 
group_by(Stimulation) %>%
summarise_all("mean")

sorted_cor = as.matrix(df4[,2:6])
rownames(sorted_cor) <- c("ATP", "DEX", "IFNy", "IL4", "LPS", "R848", "TNFa", "unstim", "ununstim")
sorted_final <- t(sorted_cor)
```
# cluster column = T, rows = F

```{r loadings_heatmap_means, echo = TRUE, width = 50, height = 6, res = 300, units = "in"}
# pdf(paste0(work_plots, "HM_markers_255s.pdf"), width = 10, height = 6)
colPalette <- colorRampPalette(rev(brewer.pal(5, "RdYlBu")))(15)
Heatmap(sorted_final,
        col = colPalette,
        name = "log2(TPM+1)", # Legend title
        cluster_rows = F,
        cluster_columns = T,
        #  row_names_gp = gpar(fontsize = 6), # Text size for row names)
        show_column_dend = T, 
        show_column_names = T,
        show_row_names = T)
#dev.off()
```

# cluster row = T, columns = F

```{r loadings_heatmap_means2, echo = TRUE, width = 50, height = 6, res = 300, units = "in"}
# pdf(paste0(work_plots, "HM_markers_255s.pdf"), width = 10, height = 6)
colPalette <- colorRampPalette(rev(brewer.pal(5, "RdYlBu")))(15)
Heatmap(sorted_final,
        col = colPalette,
        name = "log2(TPM+1)", # Legend title
        cluster_rows = T,
        cluster_columns = F,
        #  row_names_gp = gpar(fontsize = 6), # Text size for row names)
        show_column_dend = T, 
        show_column_names = T,
        show_row_names = T)
#dev.off()
```

# cluster column and row = T

```{r loadings_heatmap_means3, echo = TRUE, width = 50, height = 6, res = 300, units = "in"}
# pdf(paste0(work_plots, "HM_markers_255s.pdf"), width = 10, height = 6)
colPalette <- colorRampPalette(rev(brewer.pal(5, "RdYlBu")))(15)
Heatmap(sorted_final,
        col = colPalette,
        name = "log2(TPM+1)", # Legend title
        cluster_rows = T,
        cluster_columns = T,
        #  row_names_gp = gpar(fontsize = 6), # Text size for row names)
        show_column_dend = T, 
        show_column_names = T,
        show_row_names = T)
#dev.off()
```



