---
title: "Markers neurotransmitters"
author: "Gijsje"
date: "2/24/2021"
output: 
 rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r load.packages, echo=FALSE, message=FALSE, results='hide'}
library(readxl)
library(edgeR)
library(limma)
library(DESeq2)
library(tidyverse)
library(data.table)


knitr::opts_chunk$set( 
  warning=FALSE,
  message=FALSE,
  results = 'asis',
  error = FALSE,
  tidy = FALSE,
  fig.show = "hold")
```


```{r data_load, echo = TRUE, results = 'hide'}
load("~/Documents/MiGASti/Databases/gene_matrix.RData")
metadata <- read.table("~/Documents/MiGASti/Databases/metadata.txt")
#set rownames to Sample
row.names(metadata) <- metadata$Sample 
setwd("~/Documents/MiGASti/Databases")
exclude <- read.table("samples2remove.txt")
exclude <- exclude$x
genes_tpm_filt = genes_tpm[, !colnames(genes_tpm) %in% exclude] 
#Excludes the samples from filters. 
#dim(genes_tpm_filt)
metadata_filt = metadata[ !(rownames(metadata) %in% exclude), ]
length(metadata_filt)
#check for expression of markers in dataset
markers = "~/Documents/MiGASti/Databases/Markers_neurotransmitters.xlsx"
markers = read_excel(markers, col_names = TRUE) 
markers = as.data.frame(markers)
gencode_30 = read.table("~/Documents/MiGASti/Databases/ens.geneid.gencode.v30")
colnames(gencode_30) = c("ensembl","symbol")
genes_tpm_filt = log2((genes_tpm_filt) + 1)
genes_tpm_filt <- as.data.frame(genes_tpm_filt)
setDT(genes_tpm_filt, keep.rownames = "ensembl")
genes_tpm_filt$ensembl
res_name = merge(genes_tpm_filt, gencode_30, by="ensembl")
rownames(res_name) = res_name$ensembl
```


```{r data_load_markers, echo = TRUE, results = 'hide'}
marker_expression = merge(res_name, markers, by ="symbol")
dim (marker_expression)
head (marker_expression)
metadata_filt_ordered <- metadata_filt[colnames(genes_tpm_filt),]
metadata_filt_ordered = metadata_filt_ordered[-1,]
all(rownames(metadata_filt_ordered) == colnames (genes_tpm_filt)) #TRUE
Stimulation <- metadata_filt_ordered$Stimulation
```

### Boxplot  MAOA

```{r MAOA, echo = TRUE}
MAOA <- marker_expression[1, ] 
MAOA$ensembl = NULL
MAOA$symbol = NULL
MAOA_new<-as.data.frame(t(MAOA))
df = data.frame(Stimulation, MAOA_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("MAOA") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```


### Boxplot  SLC18A1 (Vescicular monoamine transporter 1)

```{r data_load_SLC18A1, echo = TRUE}
SLC18A1 <- marker_expression[2, ] 
SLC18A1$ensembl = NULL
SLC18A1$symbol = NULL
SLC18A1_new<-as.data.frame(t(SLC18A1))
df = data.frame(Stimulation, SLC18A1_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("SLC18A1") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```

### Boxplot SLC6A2 

```{r data_load_SLC6A2, echo = TRUE}
SLC6A2 <- marker_expression[3, ] 
SLC6A2$ensembl = NULL
SLC6A2$symbol = NULL
SLC6A2_new<-as.data.frame(t(SLC6A2))
df = data.frame(Stimulation, SLC6A2_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("SLC6A2") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```

### Boxplot SLC6A3 (Dopamine transporter)

```{r data_load_SLC6A3, echo = TRUE}
SLC6A3 <- marker_expression[4, ] 
SLC6A3$ensembl = NULL
SLC6A3$symbol = NULL
SLC6A3_new<-as.data.frame(t(SLC6A3))
df = data.frame(Stimulation, SLC6A3_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("SLC6A3") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```

### Boxplot SLC6A4

```{r data_load_SLC6A4, echo = TRUE}
SLC6A4 <- marker_expression[5, ] 
SLC6A4$ensembl = NULL
SLC6A4$symbol = NULL
SLC6A4_new<-as.data.frame(t(SLC6A4))
df = data.frame(Stimulation, SLC6A4_new)
ggplot(data = df, mapping = aes(x = Stimulation, y = V1)) +
  geom_boxplot()+ 
  ggtitle("SLC6A4") +
  xlab("Stimulation") + ylab("log2((TPM)+1)")
```









